Fix environment variables

diff --git a/.github/workflows/build-and-deploy-ios.yml b/.github/workflows/build-and-deploy-ios.yml
--- a/.github/workflows/build-and-deploy-ios.yml
+++ b/.github/workflows/build-and-deploy-ios.yml
@@ -42,18 +42,25 @@ jobs:
       - name: Download certificate and provisioning profile
         env:
           APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
-          IOS_DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.IOS_DISTRIBUTION_PROVISIONING_PROFILE }}
           APPLE_DISTRIBUTION_CERTIFICATE_PATH: ${{ runner.temp }}/DanielLupianezCasaresAppleDistribution.p12
-          IOS_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/91c38691-711a-4d00-8399-5c8b4c9e6e32.mobileprovision
+          IOS_DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.IOS_DISTRIBUTION_PROVISIONING_PROFILE }}
+          IOS_DISTRIBUTION_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/91c38691-711a-4d00-8399-5c8b4c9e6e32.mobileprovision
             
         run: |
-          echo -n "$APPLE_DISTRIBUTION_CERTIFICATE" | base64 --decode -o $APPLE_DISTRIBUTION_CERTIFICATE_PATH
-          echo -n "$IOS_DISTRIBUTION_PROVISIONING_PROFILE" | base64 --decode -o $IOS_DISTRIBUTION_PROVISIONING_PROFILE_PATH
+          if ! printf "%s" "$APPLE_DISTRIBUTION_CERTIFICATE" | base64 --decode -o "$APPLE_DISTRIBUTION_CERTIFICATE_PATH"; then
+            echo "Failed to decode Distribution Certificate" >&2
+            exit 1
+          fi
+
+          if ! printf "%s" "$IOS_DISTRIBUTION_PROVISIONING_PROFILE" | base64 --decode -o "$IOS_DISTRIBUTION_PROVISIONING_PROFILE_PATH"; then
+            echo "Failed to decode Provisioning Profile" >&2
+            exit 1
+          fi
 
       - name: Build Xcode Project using fastlane
         env:
           APPLE_DISTRIBUTION_CERTIFICATE_PATH: ${{ runner.temp }}/DanielLupianezCasaresAppleDistribution.p12
-          IOS_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/91c38691-711a-4d00-8399-5c8b4c9e6e32.mobileprovision
+          IOS_DISTRIBUTION_PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/91c38691-711a-4d00-8399-5c8b4c9e6e32.mobileprovision
 
         run: |
           cd ./iOS-Xcodeproj
@@ -61,6 +68,6 @@ jobs:
             output_name:"AppleAuth_${{ inputs.unity_version }}.ipa" \
             certificate_path:"$APPLE_DISTRIBUTION_CERTIFICATE_PATH" \
             certificate_password:"${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}" \
-            provisioning_profile_path:"$IOS_PROVISIONING_PROFILE_PATH" \
+            provisioning_profile_path:"$IOS_DISTRIBUTION_PROVISIONING_PROFILE_PATH" \
             keychain_name:"${{ secrets.KEYCHAIN_NAME }}" \
             keychain_password:"${{ secrets.KEYCHAIN_PASSWORD }}"
