Focus on windows now

diff --git a/.github/workflows/unity-build.yml b/.github/workflows/unity-build.yml
--- a/.github/workflows/unity-build.yml
+++ b/.github/workflows/unity-build.yml
@@ -66,7 +66,8 @@ jobs:
           targetPlatform: ${{ inputs.target_platform }}
           unityVersion: ${{ inputs.unity_version }}
 
-      - name: Setup fastlane files
+      - name: Setup fastlane files (macOS/Linux)
+        if: runner.os == 'macOS' || runner.os == 'Linux'
         run: |
           if [ ! -d "${{ inputs.output_path }}" ]; then
             echo "Error: Destination directory ${{ inputs.output_path }} does not exist!" >&2
@@ -79,6 +80,22 @@ jobs:
           fi
             
           sudo cp -r ./.github/${{ inputs.target_platform }}/fastlane ${{ inputs.output_path }}/fastlane
+
+      - name: Setup fastlane files (Windows)
+        if: runner.os == 'Windows'
+        shell: pwsh
+        run: |
+          if (-Not (Test-Path "${{ inputs.output_path }}")) {
+            Write-Error "Error: Destination directory ${{ inputs.output_path }} does not exist!"
+            exit 1
+          }
+      
+          if (Test-Path "${{ inputs.output_path }}/fastlane") {
+            Write-Error "Error: fastlane directory already exists in ${{ inputs.output_path }}!"
+            exit 1
+          }
+      
+          Copy-Item -Recurse -Path ".github/${{ inputs.target_platform }}/fastlane" -Destination "${{ inputs.output_path }}/fastlane"
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
